language: scala
scala:
   - 2.11.11
jdk:
  - jdk8
  - openjdk8

matrix:
  fast_finish: true

  include:
    - language: python
      python: 2.7

      install:
        - sbt assembly
        - mkdir -p python/jars
        - cp target/**/spark-api-assembly-*.jar python/jars
        - cd python
        - pip install -r requirements.txt

      script:
        - python -m unittest discover -v

      after_success:
        - echo "" # noop to avoid executing the one from the main build

    - language: python
      python: 3.6

      install:
        - sbt assembly
        - mkdir -p python/jars
        - cp target/**/spark-api-assembly-*.jar python/jars
        - cd python
        - pip install -r requirements.txt

      script:
        - python -m unittest discover -v

      after_success:
        - echo "" # noop to avoid executing the one from the main build

      before_deploy:
        - echo "$TRAVIS_TAG" | cut -c 2- > version.txt

      deploy:
        provider: pypi
        user: $PYPI_USERNAME
        password: $PYPI_PASSWORD
        server: https://test.pypi.org/legacy/
        skip_cleanup: true
        on:
          tags: true

script:
  - sbt ++$TRAVIS_SCALA_VERSION jacoco:cover
after_success:
  - bash <(curl -s https://codecov.io/bash)